# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(default='', max_length=250)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=150, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(default='', max_length=250)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(default='', max_length=250)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilterSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(default='', max_length=250)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=10)),
                ('filtercategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.FilterCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(default='', max_length=250)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=150, verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(default='', max_length=250)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('published', models.BooleanField(default=True)),
                ('filtercat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.FilterCategory')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product')),
                ('value', models.ManyToManyField(blank=True, to='goods.FilterSelect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProprty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(default='', max_length=250)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('published', models.BooleanField(default=True)),
                ('value', models.CharField(default='', max_length=50, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('categoryprop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.CategoryProperty')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
