# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproperty',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='categoryproperty',
            name='published',
        ),
        migrations.RemoveField(
            model_name='filtercategory',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='filtercategory',
            name='published',
        ),
        migrations.RemoveField(
            model_name='filterselect',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='filterselect',
            name='published',
        ),
        migrations.RemoveField(
            model_name='productfilter',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='productfilter',
            name='published',
        ),
        migrations.RemoveField(
            model_name='productproprty',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='productproprty',
            name='published',
        ),
    ]
