# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20170701_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfilter',
            old_name='filtercat_id',
            new_name='filtercat',
        ),
    ]
