# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20170701_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
