# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20170701_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
