# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20170701_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='\u0425\u0438\u0442'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='\u041d\u043e\u0432\u0438\u043d\u043a\u0430'),
        ),
    ]
