# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20170701_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='filtercat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_select_product', to='goods.FilterCategory'),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='value',
            field=models.ManyToManyField(blank=True, related_name='filtervalues', to='goods.FilterSelect'),
        ),
    ]
