# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20170702_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
